### ISSUE TITLE
`getText` fails on Linux / Ubuntu

### ISSUE THREAD

**Issue by seanpoulter** [webdriverio-community/wdio-vscode-service#103]
I found this while reviewing #94.

### Problem

We assume the command to copy from the terminal is <kbd>Ctrl</kbd>-<kbd>-c</kbd>:

```
[chrome 114.0.5735.289 linux #0-0] » /test/specs/bottombar.e2e.ts
[chrome 114.0.5735.289 linux #0-0] bottombar
[chrome 114.0.5735.289 linux #0-0]    ✖ can read from terminal @skipWeb
```

### Proposal

* On Linux use <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>-c</kbd>
* **or** Add an option that allows the user to choose what command to use to copy from the terminal
* **or** Use the Edit > Copy menu

**Comment by christian-bromann** [comment]
Thanks for raising the issue. I think all proposals make sense and we should pick whichever is more reliable.
