### ISSUE TITLE
Question: Unit, Integration, and End-to-end Testing

### ISSUE THREAD

**Issue by bmingles** [webdriverio-community/wdio-vscode-service#129]
I'm planning to use `wdio-vscode-service` for implementing end-to-end tests for a `vscode` extension. I also have `@vscode/test-electron` installed as part of the `vscode` docs on testing extensions. My original plan was something like:

* e2e tests -  `wdio-vscode-service`
* integration tests -`@vscode/test-electron` (if this makes sense)
* unit tests - also `@vscode/test-electron` (same)

My questions:
1. For integration tests, does `@vscode/test-electron` offer anything that can't be done with `wdio-vscode-service`?
2. Same question for unit tests. I'm assuming it is not the best option, so also curious if there are any best practice recommendations here.

**Comment by christian-bromann** [comment]
I am honestly not sure how "useful" `@vscode/test-electron` actually is, while you can run tests within a VSCode extension context, I would honestly either just write end-to-end tests for things that require interaction with VSCode APIs or write unit tests which mock out the VSCode interfaces. There is nothing you couldn't do with `wdio-vscode-service` that `@vscode/test-electron` can do. This package provides much better reporting capabilities and a richer ecosystem in general.

I will go ahead and close this issue but happy to provide further guidance.

**Comment by bmingles** [comment]
@christian-bromann thanks for the confirmation.

Any precedence on what to use for unit tests? Also, any consideration on enabling github discussions on this repo? Not sure how often you get question tickets.

**Comment by christian-bromann** [comment]
> Any precedence on what to use for unit tests?

I am a big fan of Vitest, great tool and community. 

> Also, any consideration on enabling github discussions on this repo?

I think so far it has been ok, but definitely something worth to consider.
