### ISSUE TITLE
browserVersion: 'insiders' is actually not running insiders

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/wdio-vscode-service#27]
All our insiders builds run with latest VS Code stable but not insiders.

**Comment by mattseddon** [comment]
I had a look and I think the easiest thing to do would be to copy the approach taken by `@vscode/test-electron` (see https://github.com/microsoft/vscode-test/blob/main/lib/util.ts#L42).

Is there an easy way to test the download after updating the code? Looks like `test:e2e` doesn't run the download. If you let me know I'll patch and open a PR.

👍🏻.

**Comment by christian-bromann** [comment]
> Looks like `test:e2e` doesn't run the download.

It should, make sure to delete the `.wdio-vscode-service` folder as it caches the binaries.

**Comment by christian-bromann** [comment]
Something must be up [here](https://github.com/webdriverio-community/wdio-vscode-service/blob/main/src/launcher.ts#L195-L210) where we try to get the tag for `insiders`. It finds that tag by visiting https://api.github.com/repos/microsoft/vscode/releases/latest and checking the `tag_name`. My hunch is that this approach is flawed because `insiders` is not always the last released artifact in that repository. The problem is that we need the insiders tag to be able to fetch the right [`cgmanifest.json` ](https://raw.githubusercontent.com/microsoft/vscode/1.69.0/cgmanifest.json) file which tells us which Chromedriver to download.

**Comment by mattseddon** [comment]
`@vscode/test-electron` actually uses a different API: `https://update.code.visualstudio.com/latest/${platform}/insider`

**Comment by christian-bromann** [comment]
@mattseddon getting `insiders` is not the problem but finding out which Chromium version is used within it so we can download the correct Chromedriver version is.

**Comment by mattseddon** [comment]
Sorry I didn't fully understand the problem. I've read the code again and raised #29. LMK what you think. Thanks
