### ISSUE TITLE
--disable-extensions flag

### ISSUE THREAD

**Issue by meguia-sfdc** [webdriverio-community/wdio-vscode-service#31]
As by default webdriver starts vscode with `--disable-extension` flag, I need to reload the window to make extensions work. I add the code to reload the window at `beforeSuite` method. My question is why are extensions disabled? Could we remove the flag?
See https://github.com/webdriverio-community/wdio-vscode-service/blob/5c6e943315f450cf089ae595085a0d37d6a069af/src/constants.ts#L14

**Comment by christian-bromann** [comment]
Thanks for raising the issue!

I believe my intention was to ensure that the extension is tested in isolation. Can you explain what your use case is? I am keen to make this behavior more dynamic, what would you suggest?

**Comment by meguia-sfdc** [comment]
As [Extension Manifest definition](https://code.visualstudio.com/api/references/extension-manifest) (see `extensionDependencies` field) supports dependencies between extensions, it could be the case that you need another extension to make your extension work. I understand that you could not support the feature and that is.

Anyway, as it's currently working, the extension under test is not activated at first: I added some `await driver.pause(60000)` to review the extension status and I got this:
<img width="928" alt="extension-disabled" src="https://user-images.githubusercontent.com/88151824/183120090-3ca1ce90-85dc-4c0b-8778-a303394b38cf.png">

So, for making it work, I needed to add the click on the warning message to reload the vscode instance at `beforeSuite` method:
<img width="455" alt="extension-warning" src="https://user-images.githubusercontent.com/88151824/183120224-00dbf776-b6c2-402c-9df9-9d012a43363e.png">

I would remove the extension disabled option by default. I see that the change was included in some windows compatibility fix. Is it part of it?

**Comment by christian-bromann** [comment]
@meguia-sfdc I don't mind making this configurable. Any contributions would be welcome! I'ld suggest though to keep `disableExtensions` as default because it just makes it much easier to debug extensions.

**Comment by meguia-sfdc** [comment]
Passing `vscodeArgs: { "disableExtensions": false }` translates into `--disable-extensions=false --disableExtensions=false` which makes it run with extensions enabled. Thanks!

**Comment by meguia-sfdc** [comment]
I think this comment could be related to this default configuration.
https://github.com/webdriverio-community/wdio-vscode-service/blob/c9e77274b364ca572358fd77122fad8a20c9db9a/test/specs/basic.e2e.ts#L184-L186

**Comment by christian-bromann** [comment]
> I think this comment could be related to this default configuration.

The test extension is usually always loaded.
