### ISSUE TITLE
Provided binary setting is ignored if versions.txt file exists

### ISSUE THREAD

**Issue by mbehr1** [webdriverio-community/wdio-vscode-service#37]
On the 2nd call / when the versions.txt file exists the provided binary settings gets overwritten/ignored/not used.

Imho line:
https://github.com/webdriverio-community/wdio-vscode-service/blob/54cb76ff746f01948dacca9cef8cd9209e827b42/src/launcher.ts#L165

should be changed e.g. to
`cap[VSCODE_CAPABILITY_KEY].binary = cap[VSCODE_CAPABILITY_KEY].binary || await this._downloadVSCode(content[version]?.vscode as string)`

**Comment by christian-bromann** [comment]
@mbehr1 makes sense to me, mind raising a PR?

**Comment by mbehr1** [comment]
will do so!

**Comment by mbehr1** [comment]
@christian-bromann  see PR#38. Tried to follow same coding style.
