### ISSUE TITLE
Npm founds 4 vulnerabilities (3 moderate, 1 high)

### ISSUE THREAD

**Issue by steinholtzNet** [webdriverio-community/wdio-vscode-service#42]
My version of wdio-vscode-service is 4.0.7
Get the following information on running npm audit fix

```
node_modules/download/node_modules/got
  download  >=4.0.0
  Depends on vulnerable versions of got
  node_modules/download

undici  <=5.8.1
Severity: high
undici before v5.8.0 vulnerable to CRLF injection in request headers - https://github.com/advisories/GHSA-3cvr-822r-rqcc
ProxyAgent vulnerable to MITM - https://github.com/advisories/GHSA-pgw7-wx7w-2w33
`undici.request` vulnerable to SSRF using absolute URL on `pathname` - https://github.com/advisories/GHSA-8qr4-xgw6-wmr3
Nodejs ‘undici’ Vulnerable to CRLF Injection via Content-Type - https://github.com/advisories/GHSA-f772-66g8-q5h3
undici before v5.8.0 vulnerable to uncleared cookies on cross-host / cross-origin redirect - https://github.com/advisories/GHSA-q768-x9m6-m9qp
No fix available
node_modules/undici
  wdio-vscode-service  *
  Depends on vulnerable versions of download
  Depends on vulnerable versions of undici
  node_modules/wdio-vscode-service

4 vulnerabilities (3 moderate, 1 high)
```

Updating the mentioned dependent packages inside of package-lock.json removed these vulnerabilities for me.

Might want to check your dependencies! :)

**Comment by christian-bromann** [comment]
> Might want to check your dependencies! :)

Might want to raise a PR?

**Comment by steinholtzNet** [comment]
Do not seem to have the access rights, just tried to push up to a new branch. 
Changing the undici version to 5.10.0 solves the vulnerability that is high.

Regarding the other it is due to the use of the download package, which itself has a dependency to an old got version.
Looking into this opened PR in downloads repo, we can hope that it is something that will soon be solved: https://github.com/kevva/download/pull/220

**Comment by christian-bromann** [comment]
> Do not seem to have the access rights, just tried to push up to a new branch.

You do not need access rights, just follow this guide: https://opensource.com/article/19/7/create-pull-request-github

**Comment by steinholtzNet** [comment]
Thank you!
First time contribute to a project :) 

https://github.com/webdriverio-community/wdio-vscode-service/pull/44

**Comment by christian-bromann** [comment]
> First time contribute to a project :)

Awesome, let's continue our convo in #44
