### ISSUE TITLE
executeCommand() runs the first matching command, not the command itself

### ISSUE THREAD

**Issue by jeffb-sfdc** [webdriverio-community/wdio-vscode-service#48]
The extension I work on is pretty complicated, and has many commands.  I'm attempting to automate running one of the commands but I'm finding that when the text of the command is passed to executeCommand(), a "fuzzy match" is performed and the first matching command runs, not the command I specified.

Steps to reproduce:
1. Let's say an extension has the following commands:
Create and Set Up Project
Create Project
Create Project with Boilerplate Example

2. Type SHIFT-CMD-P and open the command palette
3. Type, Create Project
-> Notice how VS Code filters the commands, and how that the commands that appear are the same that are listed in step 1, and appear in the same order
4. Now write some e2e test code, and add the following:
```
const workbench = await browser.getWorkbench();
const command = 'Create Project';
// await workbench.executeCommand(command);
const prompt = await workbench.openCommandPrompt();
await prompt.setText(`>${command}`);
await prompt.confirm();
```

5. And now run this test and execute this code

Result:
`await workbench.openCommandPrompt()` opens the command palette
...and `prompt.setText()` sets the text to ">Create Project"
...however, this filters the list and displays _all matching_ commands.  The first command listed is "Create and Set Up Project", and when `prompt.confirm()` executes, the first command listed runs, which in this case is "Create and Set Up Project", not "Create Project"

**Comment by jeffb-sfdc** [comment]
The implementation for `executeCommand()` is:

```
    async executeCommand (command: string): Promise<void> {
        const prompt = await this.openCommandPrompt()
        await prompt.setText(`>${command}`)
        await prompt.confirm()
    }
```

A possible fix for this would be to change executeCommand() to:

```
        const prompt = await this.openCommandPrompt()
        await prompt.setText(`>${command}`)
        const quickPicks = await prompt.getQuickPicks()
        for (const quickPick of quickPicks) {
            const label = await quickPick.getLabel()
            if (label === command) {
                await quickPick.select()
                return
            }
        }

        throw new Error('Command not found')
```

@christian-bromann your thoughts?

**Comment by christian-bromann** [comment]
How about this interface:

- `async executeCommand (command: string): Promise<void>`: basically what we have right now
- `async executeQuickPick (label: RegExp): Promise<void>`: runs the command matching the quick pick label, if no label matches, throw an error
?

**Comment by jeffb-sfdc** [comment]
I posted https://github.com/webdriverio-community/wdio-vscode-service/pull/49 to address this issue.

**Comment by christian-bromann** [comment]
Let's continue convo in #49
