### ISSUE TITLE
Continue support for CommonJS

### ISSUE THREAD

**Issue by mattseddon** [webdriverio-community/wdio-vscode-service#58]
Trying to use v5 of the service with a CommonJS module results in:

```
Error: Error: Cannot find module '/path/to/node_modules/wdio-vscode-service/dist/cjs/index.js'`
```

I've seen that `package.json` is set up to handle both ESM and CommonJS versions but I think the build needs to be updated to produce the different types.

**Comment by mattseddon** [comment]
Can you please let me know when you update Marquee to use v5?

**Comment by christian-bromann** [comment]
We are using it in a different extension already: https://github.com/stateful/vscode-runme

**Comment by mattseddon** [comment]
I've got close enough to getting over the hump (in https://github.com/iterative/vscode-dvc/pull/3005) that we can close this. Thanks for the working example.

**Comment by christian-bromann** [comment]
Awesome, great to see the update went smooth.

**Comment by mattseddon** [comment]
Thank you. Definitely took me double digit hours to finally make it work.
