### ISSUE TITLE
OpenContextMenu fails on macos 

### ISSUE THREAD

**Issue by Manushenkov** [webdriverio-community/wdio-vscode-service#79]
element (".monaco-menu-container") still not displayed after 5000ms

I tested the same code on my linux machine with the same node version and it works correctly

macos version 13.3 (22E252)
node version v19.9.0

**Comment by Manushenkov** [comment]
It does open the context menu, i can see it visually, but it can't detect it

**Comment by christian-bromann** [comment]
Thanks for reporting!

We greatly appreciate any contributions that help resolve the bug. While we understand that active contributors have their own priorities, we kindly request your assistance if you rely on this bug being fixed. We encourage you to take a look at our [contribution guidelines](https://webdriver.io/docs/contribute) or join our friendly [Discord](http://discord.webdriver.io/) development server, where you can ask any questions you may have. Thank you for your support, and cheers!

**Comment by Manushenkov** [comment]
old bug https://github.com/webdriverio-community/wdio-vscode-service/issues/57
