### ISSUE TITLE
Support HTTP_PROXY

### ISSUE THREAD

**Issue by openscript** [webdriverio-community/wdio-vscode-service#86]
Unfortunately I need to run the tests in an environment, where I can only access the internet through a proxy. `wdio-vscode-service` uses `undici` for it's requests. `undici` doesn't support the most common way to define proxies: https://github.com/nodejs/undici/issues/1650

It doesn't look like `undici` will support this any time soon. Native fetch is slowly arriving, but types are not included for Node 18. `node-fetch` would work, as it supports HttpAgents.

Is there another workaround I haven't thought of?

https://github.com/webdriverio-community/wdio-vscode-service/blob/17522803666322102a9a082512792dd030d667dc/src/launcher.ts#L8C26-L8C32

**Comment by openscript** [comment]
I decided against switching to `node-fetch` as the API of `undici` should be on par.

**Comment by christian-bromann** [comment]
Thanks for raising a PR. It is merged and will be released next.
